VIX-3179 Create Fixture Property Editor
VixenLights/Vixen pull request #308
Opened 2022-05-05 23:13 UTC by johncbaur

VIX-3179 Create Fixture Property Editor

2022-05-07 20:36 UTC, jeffu231 commented
Looks like this one needs rebased for the changes in VIX-3076

2022-05-08 14:09 UTC, johncbaur commented
Should be rebased now.

2022-05-09 23:05 UTC, jeffu231 requested changes
There is a lot to look over here. It looks pretty sensible scanning over it. Just one minor observation that caught my eye.

2022-05-10 00:17 UTC, johncbaur commented on Modules/Editor/FixturePropertyEditor/Views/SelectFixtureSpecificationView.xaml
> +                    <SolidColorBrush x:Key="{x:Static SystemColors.InactiveSelectionHighlightBrushKey}" Color="#FF333333"/>
I copied that style from LayerEditor generic.xaml.  I am presuming that we should move that style to the Theme.xaml and then try to incorporate the constant colors?  Do you want me to modify the LayerEditor as part of resolving this comment or write a new ticket for that?

2022-05-29 14:10 UTC, jeffu231 commented on Modules/Editor/FixturePropertyEditor/Views/SelectFixtureSpecificationView.xaml
> +                    <SolidColorBrush x:Key="{x:Static SystemColors.InactiveSelectionHighlightBrushKey}" Color="#FF333333"/>
Yes, try to refactor that up to the common theme and correct those places that have copies of it so we can make the code more consistent.

2022-05-30 14:17 UTC, johncbaur commented on Modules/Editor/FixturePropertyEditor/Views/SelectFixtureSpecificationView.xaml
> +                    <SolidColorBrush x:Key="{x:Static SystemColors.InactiveSelectionHighlightBrushKey}" Color="#FF333333"/>
I moved the ListBox style to theme.xml and removed it from the two original locations.  I also defined color constants and a brush.  I did not adjust any of the colors as that would change the look and feel.

2022-06-16 00:52 UTC, johncbaur commented
I think this ticket / branch is going to now need VIX-3200 and VIX-3201 to compile.

2022-07-02 00:51 UTC, jeffu231 approved these changes

2022-07-02 00:52 UTC, merged