VIX-2444 Added tail lines to mark bars
VixenLights/Vixen pull request #662
Opened 2024-12-25 16:47 UTC by da-markson

2024-12-26 17:29 UTC, jeffu231 requested changes
While testing this I found some unusual behavior with one of the alignment methods I use frequently. It may exist on others. I will attach a video showing the setup and behavior to the issue.

I think we can leave the original icon for the Show Mark Lines, since it really only turns on the leading one. Having it show both lines might be a little misleading.

2024-12-26 18:53 UTC, da-markson commented
Yes,  please do send the video as my test cases didn't trip upon anything.

I can revert the icon,  no problem.  But with the current implementation,
that check box does turn on/off both lines.

On the formatting changes, sorry about that.  As I made the same mistake on
an earlier JIRA, I specifically reviewed my changes with respect to that,
but I guess missed it.  I will correct.

On Thu, Dec 26, 2024, 11:29 AM Jeff ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> While testing this I found some unusual behavior with one of the alignment
> methods I use frequently. It may exist on others. I will attach a video
> showing the setup and behavior to the issue.
>
> I think we can leave the original icon for the Show Mark Lines, since it
> really only turns on the leading one. Having it show both lines might be a
> little misleading.
> ------------------------------
>
> On
> src/Vixen.Modules/Editor/TimedSequenceEditor/Forms/WPF/MarksDocker/Views/MarkCollectionView.xaml
> <https://github.com/VixenLights/Vixen/pull/662#discussion_r1898018115>:
>
> In the future, please try to avoid broad formatting changes incorporated
> with the logic changes. It takes extra effort to try and determine what
> changed when the broad whitespace and logic changes are mixed. If
> formatting changes are desired, please include just the formatting change
> in a separate commit that calls out the only changes are formatting.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/VixenLights/Vixen/pull/662#pullrequestreview-2523348026>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BMJ3GZWP7LJUV6GD527DNSL2HQ4I5AVCNFSM6AAAAABUGESULCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRTGM2DQMBSGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-27 18:06 UTC, jeffu231 commented
I agree the use case could go either way on the icon. I waffled back and forth and then figured it might be best to just leave it the same. 

I attached the video to the JIRA issue. No need to go back and mess with fixing the white space on this one at this point. That is just wasted effort.

2025-01-20 02:15 UTC, da-markson commented on src/Vixen.Modules/Editor/TimedSequenceEditor/Forms/WPF/MarksDocker/Views/MarkCollectionView.xaml
Completely understand.  However I do not see where I incorporated whitepsace changes, so I assume I must have some setting/configuration incorrect. Please let me know what line(s) so I update my configuration/settings.

2025-01-20 02:15 UTC, da-markson commented
Correct identified bug.

2025-01-23 19:17 UTC, jeffu231 approved these changes
Looks like the bug I found is working as the current version works. I found some other similar behavior, but it is pre-existing, so I will write that up as a separate issue. This looks good now.

2025-01-23 19:18 UTC, merged